const mongoose = require('mongoose');

/**
 * Offboarding Task Model - Departmental clearance items
 * Phase 1: Module Setup & Data Model
 */
const offboardingTaskSchema = new mongoose.Schema({
  // Reference to main offboarding request
  offboardingRequestId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'OffboardingRequest',
    required: true,
    index: true
  },
  clientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Client',
    required: true,
    index: true
  },
  employeeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee',
    required: true,
    index: true
  },

  // Task Details
  taskName: {
    type: String,
    required: true,
    maxlength: 200
  },
  taskDescription: {
    type: String,
    maxlength: 1000
  },
  taskType: {
    type: String,
    enum: [
      'document_collection',
      'asset_return',
      'access_revocation',
      'knowledge_transfer',
      'clearance_approval',
      'final_settlement',
      'exit_interview',
      'compliance_check',
      'custom'
    ],
    required: true
  },

  // Department and Assignment
  department: {
    type: String,
    enum: ['hr', 'finance', 'it', 'admin', 'compliance', 'legal', 'security', 'facilities'],
    required: true,
    index: true
  },
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  assignedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  // Status and Priority
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'blocked', 'cancelled', 'overdue'],
    default: 'pending',
    index: true
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },

  // Timeline
  dueDate: {
    type: Date,
    required: true,
    index: true
  },
  estimatedHours: {
    type: Number,
    min: 0,
    default: 1
  },
  actualHours: {
    type: Number,
    min: 0
  },
  startedAt: Date,
  completedAt: Date,

  // Dependencies
  dependsOn: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'OffboardingTask'
  }],
  blockedBy: [{
    taskId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'OffboardingTask'
    },
    reason: String
  }],

  // Completion Details
  completionNotes: {
    type: String,
    maxlength: 1000
  },
  completedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  verifiedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  verifiedAt: Date,
  requiresVerification: {
    type: Boolean,
    default: false
  },

  // Attachments and Evidence
  attachments: [{
    fileName: String,
    fileUrl: String,
    fileType: String,
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],

  // Checklist Items
  checklist: [{
    item: {
      type: String,
      required: true
    },
    completed: {
      type: Boolean,
      default: false
    },
    completedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    completedAt: Date,
    notes: String
  }],

  // Notifications and Reminders
  remindersSent: [{
    sentAt: {
      type: Date,
      default: Date.now
    },
    sentTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    reminderType: {
      type: String,
      enum: ['due_soon', 'overdue', 'escalation']
    }
  }],
  escalationLevel: {
    type: Number,
    default: 0,
    min: 0,
    max: 3
  },

  // Comments and Communication
  comments: [{
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    content: String,
    addedAt: {
      type: Date,
      default: Date.now
    },
    isInternal: {
      type: Boolean,
      default: false
    }
  }],

  // Automation and Integration
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  templateId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'TaskTemplate'
  },
  integrationData: {
    type: mongoose.Schema.Types.Mixed
  },

  // Metrics
  completionPercentage: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for performance
offboardingTaskSchema.index({ offboardingRequestId: 1, department: 1 });
offboardingTaskSchema.index({ assignedTo: 1, status: 1 });
offboardingTaskSchema.index({ dueDate: 1, status: 1 });
offboardingTaskSchema.index({ clientId: 1, status: 1 });

// Virtual for overdue status
offboardingTaskSchema.virtual('isOverdue').get(function() {
  if (this.status === 'completed') return false;
  return new Date() > this.dueDate;
});

// Virtual for days overdue
offboardingTaskSchema.virtual('daysOverdue').get(function() {
  if (!this.isOverdue) return 0;
  const today = new Date();
  const due = new Date(this.dueDate);
  const diffTime = today - due;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
});

// Virtual for checklist completion percentage
offboardingTaskSchema.virtual('checklistCompletion').get(function() {
  if (!this.checklist || this.checklist.length === 0) return 100;
  const completed = this.checklist.filter(item => item.completed).length;
  return Math.round((completed / this.checklist.length) * 100);
});

// Pre-save middleware
offboardingTaskSchema.pre('save', function(next) {
  // Update completion percentage based on checklist
  if (this.checklist && this.checklist.length > 0) {
    const completed = this.checklist.filter(item => item.completed).length;
    this.completionPercentage = Math.round((completed / this.checklist.length) * 100);
  }

  // Set completion date
  if (this.status === 'completed' && !this.completedAt) {
    this.completedAt = new Date();
    this.completionPercentage = 100;
  }

  // Set started date
  if (this.status === 'in_progress' && !this.startedAt) {
    this.startedAt = new Date();
  }

  // Check for overdue status
  if (this.status !== 'completed' && new Date() > this.dueDate) {
    this.status = 'overdue';
  }

  next();
});

// Static methods
offboardingTaskSchema.statics.getByOffboardingRequest = function(offboardingRequestId) {
  return this.find({ offboardingRequestId })
    .populate('assignedTo', 'email firstName lastName')
    .populate('completedBy', 'email firstName lastName')
    .sort({ dueDate: 1 });
};

offboardingTaskSchema.statics.getByAssignee = function(assignedTo, clientId) {
  return this.find({ assignedTo, clientId, status: { $nin: ['completed', 'cancelled'] } })
    .populate('offboardingRequestId')
    .populate('employeeId', 'firstName lastName email')
    .sort({ dueDate: 1 });
};

offboardingTaskSchema.statics.getOverdueTasks = function(clientId) {
  return this.find({
    clientId,
    status: { $nin: ['completed', 'cancelled'] },
    dueDate: { $lt: new Date() }
  }).populate('assignedTo', 'email firstName lastName')
    .populate('employeeId', 'firstName lastName email');
};

offboardingTaskSchema.statics.getDepartmentTasks = function(department, clientId) {
  return this.find({ department, clientId })
    .populate('assignedTo', 'email firstName lastName')
    .populate('employeeId', 'firstName lastName email')
    .sort({ dueDate: 1 });
};

module.exports = offboardingTaskSchema;
