services:
  mongodb:
    image: mongo:7.0
    container_name: hrms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hrms
    volumes:
      - mongodb_data:/data/db
    networks:
      - hrms-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/hrms
    depends_on:
      - mongodb
    networks:
      - hrms-network
    volumes:
      - .:/app
      - /app/node_modules


volumes:
  mongodb_data:

networks:
  hrms-network:
    driver: bridge
